apiVersion: v1
kind: ReplicationController
metadata:
  name: sphinx-ingress-rc
  labels:
    app: sphinx-ingress
  annotations:
    ncp-nsx/ingress-controller: "True"
spec:
  replicas: 1
  selector:
    app: sphinx-ingress
  template:
    metadata:
      labels:
        app: sphinx-ingress
    spec:
      containers:
      - image: nginxdemos/nginx-ingress:0.8.1
        imagePullPolicy: IfNotPresent
        name: nginx-ingress
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        args:
         - -v=3