kubeConfig:
  enabled: true
  secretName: my-kubeconfig
  secretKey: config
  contexts:
  # Names of contexts available in the uploaded kubeconfig
  - kubeignite-centos-master-003
  # This is the context from the list above that you would like
  # to deploy Spinnaker itself to.
  deploymentContext: kubeignite-centos-master-003
dockerRegistries:
- name: dockerhub
  address: index.docker.io
  repositories:
    - library/alpine
    - library/ubuntu
    - library/centos
    - library/nginx
    - hanymichael/sphinx-project
    - hanymichael/sphinx-app    
# - name: gcr
#   address: https://gcr.io
#   username: _json_key
#   password: '<INSERT YOUR SERVICE ACCOUNT JSON HERE>'
#   email: 1234@5678.com
